### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by xavierfoucrier** [xavierfoucrier/inbox-notifier#179]
Google has finally decided to block the OAuth screen authentication for **Gmail Notifier** because the application need to be entirely review with **a new brand name** that must not contain any reference that could be associated with Google, regarding the new user data policy.

**Roadmap**

- [x] find an appropriate name that best represent the goal of the application
- [x] create a new brand logo
- [x] rename/move the repository *(create an org.?)*
- [x] review the code in Visual Studio
- [x] renew the OAuth client secret code
- [x] update the OAuth validation screen

> See issue #141 for the whole history
